project:
  type: website

website:
  title: "A Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - href: sources.qmd
        text: Sources
      - href: about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



